### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by EdyWerder** [tdmrhn/blocks-scanner#1]
Hi,
 
I installed the Blocks Scanner plugin from Github, but when I open it under Tools, I get a blank page. I use Cloudflare and WP Rockets in case that helps.

It's version 0.7.2 I installed yesterday.

**Comment by tdmrhn** [comment]
Thanks for the feedback, can you see the tabs above?

Here is a blank site i tested now, does it looks like this;
![image](https://github.com/tdmrhn/blocks-scanner/assets/10661276/0078116f-a9a7-4858-8a98-18c0bbfba92b)

**Comment by EdyWerder** [comment]
Hi - I see not the fields only a blank page

![image](https://github.com/tdmrhn/blocks-scanner/assets/39064869/5e82f7d1-ab8f-4c9e-b241-87bbd980bbd4)

**Comment by tdmrhn** [comment]
If you've previously installed another version make sure to clear browser caches, if that doesn't help I can check it on your site if you give temp access to: info dmrhn dev

**Comment by EdyWerder** [comment]
Today I got an update notification in my WordPress that Blocks Scanner 0.9 is available. I updated it and now it works. Great plugin - it looks really good. I was using Find My Blocks, but it is outdated. I'm just curious: are you a Blocksy developer? I first heard about the plugin in the Blocksy FB group

**Comment by arsh999cg** [comment]
@Fafa24 Yes, Taha is an official team member for Blocksy

**Comment by EdyWerder** [comment]
Thank you!! :)

**Comment by tdmrhn** [comment]
@Fafa24 yes i am with Blocksy team but not dev.
